title: Kavish Lodha # your name (or website title) here
logo: "/images/logo.png/?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br><br>
  <a href="https://www.instagram.com/kavish.10/"><img src="/images/logohs.png.png" alt ="LOGO" ></a>
  <br><br>
  <a href="https://twitter.com/harshsinghvi29?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @harshsinghvi29</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  <br><br>
  This website in under construction.
  <br><br>
  By the time you can contact me though:-
  <br><br>
  <a href="http://linkedin.com/in/harsh-singhvi-658968a1">View My LinkedIn Profile</a>   
  <br>
  <a href="https://instagram.com/insomniac_coder?igshid=1m2jur72ucxhf">View My Instagram Profile</a> 
    <a href="https://drive.google.com/file/d/113fKyscCjzslVrqtyBUsM-87e9hajSuM/view?usp=drivesdk">MDM</a> 



plugins: ['jekyll-twitter-plugin']
theme: jekyll-theme-hacker
google_analytics: UA-146712317-1 # your Google Analytics tracking ID here
